Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -34,20 +34,22 @@ jobs:
           path: ~/.m2
           key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
           restore-keys: 
-
-      - name: Configure Maven settings
-        run: |
-          mkdir -p ~/.m2
-          echo "<settings>
-                  <servers>
-                    <server>
-                      <id>hello-world-war</id>
-                      <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
-                      <password>${{ secrets.ARTIFACTORY_API_KEY }}</password>
-                    </server>
-                  </servers>
-                </settings>" > ~/.m2/settings.xml
           
+	    # Step 1: Install Maven (if not installed already)
+      - name: Install Maven
+        run: |
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found, installing..."
+            sudo apt update
+            sudo apt install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+
+      # Step 2: Verify Maven installation
+      - name: Verify Maven installation
+        run: mvn -v
+		  
       # Build the project with Maven
       - name: Build with Maven
-        run: mvn clean deploy
+        run: mvn clean install
